#!/bin/bash

clear
echo "═══════════════════════════════════════════════════════════════════"
echo "        🎯 VIOVERSE PROFESSIONAL - CSV-DRIVEN VIOBOX SYSTEM"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ COMPLETE SYSTEM FEATURES:"
echo ""
echo "📊 CSV DATA INTEGRATION:"
echo "  • Loads violations from 3 CSV files (EQ, EX, TU)"
echo "  • Exact pixel coordinates for each viobox"
echo "  • Severity-based color coding (Extreme=Red, Severe=Orange, etc)"
echo "  • Full violation text and metadata"
echo ""
echo "🎨 PAGE GRID VISUALIZATION:"
echo "  • Gray boxes = Pages without violations"
echo "  • Orange boxes = Pages with violations (from CSV)"
echo "  • Red box with white border = Currently selected page"
echo "  • File-text icons instead of numbers"
echo "  • Hover scales to 115%"
echo ""
echo "📄 PDF RENDERING:"
echo "  • Loads actual PDFs from /data/pdfs/ directory"
echo "  • Draws vioboxes at exact CSV coordinates"
echo "  • Auto-scales to fit container"
echo "  • Shows placeholder for non-violation pages"
echo ""
echo "🔍 VIOBOX FEATURES:"
echo "  • Hover tooltip shows violation details"
echo "  • Color-coded by severity"
echo "  • Toggle visibility with 'V' key"
echo "  • Click for detailed information"
echo ""
echo "⌨️ KEYBOARD SHORTCUTS:"
echo "  • Arrow keys: Navigate pages"
echo "  • V: Toggle vioboxes on/off"
echo "  • Escape: Toggle sidebars"
echo ""
echo "📈 STATISTICS:"
echo "  • Total violations loaded from CSV"
echo "  • Violations by bureau (EQ/EX/TU)"
echo "  • Violations by severity level"
echo "  • Creditor information display"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 Starting server on http://localhost:8080"
echo "   Navigate to: http://localhost:8080/frontend/index-pro.html"
echo ""
echo "Press Ctrl+C to stop the server"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

cd /home/avid_arrajeedavey/vioverse-clean-site/public
python3 -m http.server 8080