#!/bin/bash

clear
echo "═══════════════════════════════════════════════════════════════════"
echo "       🎯 VIOBOX ALIGNMENT TEST - CSV COORDINATE VERIFICATION"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ CRITICAL FIXES APPLIED:"
echo ""
echo "1. Y-COORDINATE ADJUSTMENT:"
echo "   • CSV Y coordinate is at BOTTOM of box"
echo "   • Fixed: scaledY = (violation.y * scale) - scaledHeight"
echo "   • Matches existing working app.js behavior"
echo ""
echo "2. BASE SCALE 1.0:"
echo "   • CSV coordinates are based on scale 1.0"
echo "   • PDF renders at baseScale * zoomLevel"
echo "   • VioBoxes scale proportionally"
echo ""
echo "3. ZOOM CONTROLS:"
echo "   • '+' or '=' : Zoom In (up to 300%)"
echo "   • '-' or '_' : Zoom Out (down to 50%)"
echo "   • '0' : Reset to 100%"
echo "   • 'V' : Toggle VioBoxes on/off"
echo ""
echo "📊 TEST VIOLATIONS TO VERIFY:"
echo ""
echo "AL-EQ-2024-04-25-P57.pdf:"
echo "  • Location: x=35, y=202.3, w=252, h=8"
echo "  • Severity: Extreme (Red border)"
echo "  • Text: 'Account Status INCLUDED_IN_CHAPTER_13'"
echo ""
echo "AL-EX-2024-04-25-P05.pdf:"
echo "  • Location: x=99.99, y=315.4, w=368.64, h=24.95"
echo "  • Severity: Extreme (Red border)"
echo "  • Text: 'Discharged through Bankruptcy Chapter 13'"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 Starting server..."
echo "   Navigate to: http://localhost:8080/frontend/index-pro.html"
echo ""
echo "📋 VERIFICATION STEPS:"
echo "   1. Select EX bureau, date 4/25/24"
echo "   2. Navigate to page 5 (has violations)"
echo "   3. Check that red boxes align with text on PDF"
echo "   4. Test zoom with +/- keys"
echo "   5. Verify boxes scale correctly with zoom"
echo ""
echo "Press Ctrl+C to stop the server"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

cd /home/avid_arrajeedavey/vioverse-clean-site/public
python3 -m http.server 8080